# Default configuration for mipsel-softmmu

include mips-softmmu-common.mak
CONFIG_SSI=y
CONFIG_SSI_SD=y
CONFIG_SSI_FLASH=y
CONFIG_SD=y
CONFIG_FRAMEBUFFER=y
CONFIG_LS1A_SPI=y
CONFIG_LS1A_DMA=y
CONFIG_LS1A_NAND=y
CONFIG_LS1A_RTC=y
CONFIG_LS1A_I2C=y
CONFIG_DS1338=y
CONFIG_IDE_CMD646=y
CONFIG_SYNOPSYS_GMAC=y
CONFIG_WDT_LS1A=y
CONFIG_LS1A_AC97=y
CONFIG_LS1B_DMA=y
CONFIG_LS1B_NAND=y
CONFIG_LS1A_CAN=y
CONFIG_LS2F_BONITO=y
